name: Find Unregistered Examples
on:
  schedule:
    - cron: '0 6 * * 0-6'
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
jobs:
  findUnregisteredRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
        
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: ".github/workflows/sync-integration-workflow.yml"
          from: "yaml"
          to: "json"
          
      - run: echo "${{fromJson(steps.yaml2json.output.data)}}"

      - run: echo "${{steps.yaml2json.output.data}}" >> registered-repos.txt
      - run: echo "${{fromJson(steps.yaml2json.output.data)}}" >> registered-repos.txt
      - run: echo "${{fromJson(steps.yaml2json.output.data.env.REPOSITORIES)}}" >> registered-repos.txt
        
      - run: echo "UNREGISTERED_REPOS=$(node scripts/find-unregistered-repos.js) >> $GITHUB_ENV

      - name: Notify
        uses: lazy-actions/slatify@master
        if: github.ref == 'refs/heads/main' && ${{env.UNREGISTERED_REPOS}}
        with:
          type: ${{ job.status }}
          job_name: "*Unregistered Public Repos*"
          url: ${{ secrets.BX_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_MESSAGE: "${env.UNREGISTERED_REPOS"
          SLACK_TITLE: "*Unregistered Public Repos*"
          SLACK_WEBHOOK: ${{ secrets.BX_SLACK_WEBHOOK }}
        