name: Find Unregistered Examples
on:
  schedule:
    - cron: '0 6 * * 0-6'
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
    

jobs:
  findUnregisteredRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Find All Public Repos
        uses: octokit/request-action@v2.x
        id: public_repos_not_registered
        with:
          route: GET /orgs/{owner}/repos
          owner: begin-examples
          type: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo ${{ steps.public_repos_not_registered.outputs.data }} >> public_repos.json"
        
      - run: cat public_repos.json

      - name: Find Registered Repos
        id: find_registered_repos
        uses: cumulusds@v0.1.0
        with:
          file: .github/workflows/sync-integration.yml
          registered: env.REPOSITORIES
        
      - run: "echo ${env.registered} >> registered_repos.txt"
      
      - run: cat registered_repos.txt
        