name: Find Unregistered Examples
on:
  schedule:
    - cron: '0 6 * * 0-6'
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
    

jobs:
  findUnregisteredRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Find All Public Repos
        uses: octokit/request-action@v2.x
        id: public_repos_not_registered
        with:
          route: GET /orgs/{owner}/repos
          owner: begin-examples
          type: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create-json
        id: create-json-1 # First ID
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "public_repos.json"
          json: ${{ steps.public_repos_not_registered.outputs.data }}

      - run: cat public_repos.json
        
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: public_repos.json
          contents: |
            echo "${{ steps.public_repos_not_registered.outputs.data }}"
          write-mode: overwrite
      
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: '.github/workflows/sync-integration.yml'
          from: 'yaml'
          to: 'json'
        
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: sync-integration.json
          contents: |
            echo "$${{ steps.yaml2json.output.data }}"
          write-mode: overwrite