name: Find Unregistered Examples
on:
  schedule:
    - cron: '0 6 * * 0-6'
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
    

jobs:
  findUnregisteredRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Find All Public Repos
        uses: octokit/request-action@v2.x
        id: public_repos_not_registered
        with:
          route: GET /orgs/{owner}/repos
          owner: begin-examples
          type: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo ${{ steps.public_repos_not_registered.outputs.data }} >> public_repos.json"
        
      - run: cat public_repos.json
      
      - uses: fabasoad/yaml-json-xml-converter-action@v1.0.x
        id: yaml2json
        with:
          path: '.github/workflows/sync-integration.yml'
          from: 'yaml'
          to: 'json'
        
      - run: "echo ${{steps.yaml2json.output.data}} >> sync-integration.json"
      
      - run: cat sync-integration.json
        