name: Find Unregistered Examples
on:
  schedule:
    - cron: '0 6 * * 0-6'
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
jobs:
  findUnregisteredRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1
        
      - name: Convert workflow to json
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: ".github/workflows/sync-integration-workflow.yml"
          from: "yaml"
          to: "json"

      - name: Find Registered Repos
        run: echo "${{fromJson(steps.yaml2json.outputs.data).env.REPOSITORIES}}" >> registered-repos.txt
        
      - name: Install for scripts
        run: "cd scripts; npm install"
        
      - name: find unregistered repos
        run: "echo '{{$(node scripts/find-unregistered-repos.js)}}' | tee unregistered-repos.txt "

      - name: Count Unregistered
        run: echo "count_unregistered=$(cat unregistered-repos.txt | wc -l)" >> $GITHUB_ENV

      - name: Notify
        uses: lazy-actions/slatify@master
        if: github.ref == 'refs/heads/main' && ${{env.count_unregistered>0}}
        with:
          type: ${{ job.status }}
          job_name: "*There are ${{env.count_unregistered}} unregistered repos*"
          url: ${{ secrets.BX_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

        