name: Find Unregistered Examples
on:
  schedule:
    - cron: '0 6 * * 0-6'
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
    

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: public_repos_not_registered
        with:
          route: GET /orgs/{owner}/repos
          owner: begin-examples
          type: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Repos Not Registered: ${{ steps.public_repos_not_registered.outputs.data }}"